### ISSUE TITLE
Расширить атрибуты объекта Field Item Selector

### ISSUE THREAD

**Issue by Evseenkova** [essence-community/core#21]
Необходимо реализовать возможность привязать сервис (атрибут updatequery) на объекте Field Item Selector по аналогии с обектом Button.

Например, на текущий момент для отправки начислений в БФЛ используется объект Send request (Button) (путь Начисления - Ведение периодов Period_org_department - Send request), который загружает сервис.

Необходимо реализовать аналогично на объекте "Мультивыбор услуг" (Field Item Selector) (путь к объекту Объектовый учёт - Объекты обслуживания по договору Con_MO_Tabs - Con_MO_Services - MO Service Contract Grid - COPY of Мультивыбор услуг)

**Comment by Honyrik** [comment]
done
