### ISSUE TITLE
Непрерывный вызов интеграционных сервисов

### ISSUE THREAD

**Issue by vladshem** [essence-community/core#23]
- При настройке интеграционных сервисов в следующем порядке 1->2->3 шлюз должен вызывать всю цепочку, независимо от результата выполнения каждого сервиса. 

- Возвращать пользователю весь стэк ошибок, который возвращает каждый сервис

**Comment by toksy** [comment]
Такое поведение можно реализовать следующим образом: 
Для того шага в интеграционной цепочке, который необходимо пропустить с ошибкой и перейти к следующему шагу. 
в ответе вместо **cv_error** возвращать, например, **cv_error_skip** и анализировать ошибку вручную. 

В этом случае шлюз не будет прерывать цепочку вызовов.
