### ISSUE TITLE
Невозможно управлять активностью Column Checkbox

### ISSUE THREAD

**Issue by suijius** [essence-community/core#24]
Невозможно управлять активностью Column Checkbox.
Например хотим, чтобы  была возможность использовать disabledruls

Применяться будет для мультивыбора, чтобы не отмечать отдельные строки.

**Comment by toksy** [comment]
Принято в работу - CORE-1845

**Comment by toksy** [comment]
реализовано

**Comment by toksy** [comment]
Реализовано в версии 2.6.0
