### ISSUE TITLE
Кастомные параметры

### ISSUE THREAD

**Issue by Lefest** [essence-community/core#25]
Проект ЭАД
При обновлениях слетают кастомные параметры, которые приходится по новой все настраивать. Это очень не удобно.
Особенно критично:
1. Параметры доступа к страницам, в т.ч. страницам Платформы. Экшены. Приходится переключаться на внутреннюю авторизацию, для востановления доступа админа через авторизацию СУВК.
2. Парамеры редиректов и домашних страниц SYS Application - Auth

Обновление делалось через установочник.

**Comment by toksy** [comment]
п.1 - решено в версии 2.6.0, добавлен атрибут skip_update_action_page (подробнее в описании релиза) 
п.2 - данные параметры сохранять нет возможности. Альтернативное решение - склонировать себе базовое представление и в дальнейшем оно обновляться нами не будет
