### ISSUE TITLE
Пути в автоматизированной установке

### ISSUE THREAD

**Issue by Lefest** [essence-community/core#26]
Слишком жестко зашиты пути к частям платформы.
Префиксы и т д.
Хотелось бы прописывать конечный путь до нужного каталога, чтоб он не создавал еше один каталог под шлюз.
И прописывать свои имена БД, т.к. первоначально некоторые проекты жили без префиксов.

**Comment by toksy** [comment]
Пути в установщике прописываются только с префиксами, это реализовано.
По старым проектам, установленным вручную, необходимо обновить пути к БД и папкам, и тогда последующее обновление инсталлером.

**Comment by Lefest** [comment]
Непонятно в чем задумка ограничения пользователя в именовании бд?

**Comment by Lefest** [comment]
И плюс вопрос был еще в том, что напимер путь к каталогу тоже нельзя прописать свой. он дописывает еще \ungate
