### ISSUE TITLE
Редиректы внутри приложения

### ISSUE THREAD

**Issue by Lefest** [essence-community/core#28]
Прописал странице статическую ссылку main для основной странице приложения

В настройках приложений pages и auth.

в pages прописал defaultvalue как main
в auth прописал в redirect на  main

Как теперь работает.. 
Если не авторизирован
1. захожу через ссылку например корневую
редирект на auth - ввожу - он меня на /pages
где белый экран + меню.
если нажать f5 то  переводит на /pages/main 

2. захожу через ссылку левую /home
редирект на auth - ввожу -  переводит на /pages
обновляю еще раз переводит на /pages/main 

Если авторизирован 
То при переходе на любую ссылку (корневую или /home или /dfgdfg)
перекидывает на /pages. после f5 переводит на /pages/main 

Если гдде то что то поработал и закрываю вкладки, то после закрытия последней нормально оказываюсь на /pages/main 

Хотелось бы чтоб не редиректило на белые страницы.

**Comment by toksy** [comment]
Ситуация должна исправиться в - https://github.com/essence-community/core/releases/tag/2.6.2
