### ISSUE TITLE
При ошибках валидации, полученной с одной кнопки, блокируются также и другие кнопки в окне

### ISSUE THREAD

**Issue by alexey8pcd** [essence-community/core#30]
Проект ПКО

В модальном окне 2 функциональных кнопки с разными сервисами. На первой кнопке имеется строгая валидация вводимых данных, на второй - нет. При нажатии на первую, при наличие ошибок на форме, блокируется обе кнопки, а должна только одна - та, для которой вернулась ошибка валидации

![image](https://user-images.githubusercontent.com/5404210/87769953-03b9a800-c827-11ea-98b1-c2b591afb2fc.png)

**Comment by toksy** [comment]
Необходимо продумать механизм отправки формы без валидации. Плюс научить кнопку знать, что именно она отправила

**Comment by toksy** [comment]
Решено в версии 2.6.0
