### ISSUE TITLE
Динамик панель самопроизвольно вызываться при открытии модального окна (ПКО)

### ISSUE THREAD

**Issue by suijius** [essence-community/core#32]
После обновления до 2.5.2 начала динамик панель самопроизвольно вызываться при открытии модального окна, хотя автолоад отключен. Должен вызываться только если выбран мастер. На версии 2.5.0 так и было

**Comment by toksy** [comment]
ситуация должна исправиться в - https://github.com/essence-community/core/releases/tag/2.6.2 
проверьте корректность указания мастеров и атрибута idproperty
