### ISSUE TITLE
При обновлении привязки объектов на динамик панели появляется ошибка "страница не существует или нет прав" (ПКО)

### ISSUE THREAD

**Issue by suijius** [essence-community/core#33]
Не понятно, почему именно (из-за мастера или нет), но если обновление привязки сделать, то потом происходит ошибка "страница не существует или нет прав". Нужно после этого json заново формировать.

Сделал упрощенный вариант, нет ссылок на компоненты извне панели, но все равно при перепривязке объектов на странице перестало работать

Данное поведение проявляется для объекта - комбобокс

**Comment by suijius** [comment]
Страница: http://pko-dev.developers/pages/24166861
Кнопка на странице: "Создать по шаблону"
Сервис: PKOTestDynamic
Данные, возвращаемые сервисом:
SELECT '
{
  "cl_dataset": "1",
  "cv_name": "Dynamic Panel",
  "ck_page": "24166861",
  "ck_modify": "modify",
  "cv_helper_color": "red",
  "contentview": "column",
  "reqsel": "true",
  "type": "FIELDSET",
  "datatype": "array",
  "column": "_",
  "childs": [
    {
      "type": "PANEL",
      "childs": [
        {
          "type": "BOX",
          "childs": [
            {
              "type": "IFIELD",
              "column": "cn_paydoc_number",
              "ck_page": "24166861",
              "cv_name": "Поле Номер",
              "maxsize": "6",
              "cn_order": 10,
              "datatype": "text",
              "required": false,
              "ck_master": null,
              "ck_object": "7E00260BE9D06987E053129BA8C0390A",
              "ck_parent": "FC9C9F8723F544DAABE1D52C13DFE81C",
              "cl_dataset": 0,
              "cv_displayed": "3fa683657e964882bd7fb04cdafe2b2b",
              "ck_page_object": "E7F5CFEF1BFC49DF8A47E41E982F6E50",
              "cv_description": "Поле Номер"
            },
            {
              "type": "IFIELD",
              "column": "cd_paydoc_date",
              "format": "3",
              "ck_page": "24166861",
              "cv_name": "Поле даты",
              "cn_order": 20,
              "datatype": "date",
              "required": false,
              "ck_master": null,
              "ck_object": "7E00260BE9CF6987E053129BA8C0390A",
              "ck_parent": "FC9C9F8723F544DAABE1D52C13DFE81C",
              "cl_dataset": 0,
              "cv_displayed": "5ef01b208a3e4611abfaa4a11b368315",
              "ck_page_object": "387372E24032422BAD380E53C4753C1E",
              "cv_description": "Поле даты"
            },
            {
              "type": "IFIELD",
              "column": "ck_order_type",
              "ck_page": "24166861",
              "cv_name": "Поле Тип поручения",
              "maxsize": "60",
              "autoload": true,
              "ck_query": "PKOGetOrderType",
              "cn_order": 30,
              "datatype": "combo",
              "minchars": 1,
              "required": true,
              "ck_master": null,
              "ck_modify": "modify",
              "ck_object": "007A6784AFB040648E55FFEA3AD97377",
              "ck_parent": "FC9C9F8723F544DAABE1D52C13DFE81C",
              "querymode": "local",
              "setglobal": [
                {
                  "in": "ck_id",
                  "out": "g_order_type"
                }
              ],
              "cl_dataset": 1,
              "idproperty": "ck_id",
              "querydelay": 1,
              "valuefield": [
                {
                  "in": "ck_id",
                  "out": null
                }
              ],
              "cv_displayed": "eac96f86fd434df09a77b6ba6c457fee",
              "defaultvalue": "##first##",
              "displayfield": "cv_order_type",
              "noglobalmask": true,
              "ck_page_object": "6A566779C9B84034BFF108BDBDEFE5A4",
              "cv_description": "Тип поручения",
              "getmastervalue": [
                {
                  "in": "ck_id",
                  "out": "ck_id"
                }
              ],
              "orderdirection": "ASC",
              "cv_helper_color": "yellow"
            }
          ],
          "reqsel": true,
          "ck_page": "24166861",
          "cv_name": "Бокс Номер/Дата/Тип поручения",
          "cn_order": 10,
          "ck_master": null,
          "ck_object": "7E00260BE9CB6987E053129BA8C0390A",
          "ck_parent": "217A0AE99A624422BC48D0E1F4290D81",
          "cl_dataset": 0,
          "contentview": "hbox",
          "cv_displayed": null,
          "ck_page_object": "FC9C9F8723F544DAABE1D52C13DFE81C",
          "cv_description": "Номер/Дата/Тип поручения"
        }
      ],
      "reqsel": true,
      "ck_page": "24166861",
      "cv_name": "Панель Данные платежа",
      "ck_query": null,
      "cn_order": 3,
      "ck_master": null,
      "ck_modify": "modify",
      "ck_object": "7E00260BE9CA6987E053129BA8C0390A",
      "resizable": false,
      "cl_dataset": 1,
      "idproperty": "ck_id",
      "collapsible": true,
      "contentview": "vbox",
      "cv_displayed": "d70a2f13cefc4f4ababa669518540381",
      "ck_page_object": "217A0AE99A624422BC48D0E1F4290D81",
      "cv_description": "Панель Данные платежа",
      "getmastervalue": [
        {
          "in": "ck_id",
          "out": "ck_id"
        }
      ],
      "cv_helper_color": "red"
    }
  ]
}
'::json

**Comment by Honyrik** [comment]
у PKOGetOrderType сменить тип access с po_session на session что бы не было привязки проверки page object
