### ISSUE TITLE
Ошибки Core версии 2.5.3

### ISSUE THREAD

**Issue by voshilo-k** [essence-community/core#36]
описание в прилагаемом файле
[Ошибки core.docx](https://github.com/essence-community/core/files/4990478/core.docx)

[Patch_2020-07-29_09_58_09.zip](https://github.com/essence-community/core/files/4993128/Patch_2020-07-29_09_58_09.zip)

**Comment by toksy** [comment]
По порядку - 
1) причина этой ошибки пустое значение в атрибуте contentview, необходимо указывать одно из доступных
2) данные кнопки ориентируются на доступность первичного ключа в таблице, указанного в атрибуте idproperty, в Вашем случае сервис, который начитывает таблицу, данный ключ не возвращает. 
3) Проблема устранена в релизе 2.6.0
4) проблема аналогично п.2 , нет колонки , указанной в idproperty
5) Проблема была в конфликте класса Service Hidden, который не мог быть мастером для кого-либо - исправлено
