### ISSUE TITLE
Значение по умолчанию Field Date

### ISSUE THREAD

**Issue by voshilo-k** [essence-community/core#42]
[Patch_2020-08-18_11_46_27.zip](https://github.com/essence-community/core/files/5089279/Patch_2020-08-18_11_46_27.zip)
Для Field Date в defaultvalue проставлено sysdate, в format 3, но при открытии окна добавления в поле не отображается значение по умолчанию . Violation Grid -> Add Window -> COPY of dt_act_st. Страница в приложении

**Comment by toksy** [comment]
В актуальной версии функционал работает, необходимо обновиться до последнего релиза (либо дождаться слудающего)
