### ISSUE TITLE
Работа зависимых гридов

### ISSUE THREAD

**Issue by Lefest** [essence-community/core#43]
версия **2.3** - 
1.Нажимаешь на строку договора - по нему в дочернем гриде строяться доки
2. Если дочка была активироваа раньше. Нажимаешь на чек бокс, он отмечает договор для массового выбора(который потмо по кнопке Поиск делается)
3. Если она не активирована, то надо было ее сначала активировать нажав на любую строку.
в  работе версии 2.3 устраивало все, кроме последнего момента.
Версия **2.5.3** 
1. Если только зашел на страницу.
Нажимаешь на строку договора - дочка активируется. Документы данного договора не отображаются Отрабатывает как кнопка Поиск. но поскольку чек боксы пустые  - результат пустой.
2. До активации дочки. Нажимаешь на чек бокс - дочкка не активируется. Договора выбираются но дочернем гриде не отображаются
3. Нажатие на строку или кнопку поиск показывает Договора на которых галочки прокликаны

Желаемое, чтоб работало как в 2.3, но без проблемы с активацией дочернего элемента

[Patch_2020-08-20_11_28_06.zip](https://github.com/essence-community/core/files/5101720/Patch_2020-08-20_11_28_06.zip)
[Core_json.txt](https://github.com/essence-community/core/files/5101721/Core_json.txt)

**Comment by toksy** [comment]
Должно корректно работать в - https://github.com/essence-community/core/releases/tag/2.6.2
