### ISSUE TITLE
Генерация значения в поле

### ISSUE THREAD

**Issue by Evseenkova** [essence-community/core#45]
Необходимо реализовать возможность в окне добавления и редактирования данных генерировать значение в строке, с возможностью его удаления. 
Например, при нажатии на кнопку "Создать" с помощью сервиса будет генерироваться значение, например "123", затем пользователь нажатием на кнопку "Удалить" может стереть данное значение.

**Comment by toksy** [comment]
генерировать значения без сервисной части сейчас не будем
