### ISSUE TITLE
Из формы динамической панели передаются не все поля (ПКО)

### ISSUE THREAD

**Issue by alexey8pcd** [essence-community/core#47]
С помощью динамической панели создается форма в модальном окне, значения заполняются через defaultvalue. При нажатии на кнопку "Сохранить", отправляются значения только некоторых полей, остальные не отправляются. Также при отправке данных используется формат json-а, отличный от статических форм.
Страница: http://pko-dev.developers/pages/24166861

Ожидаемое поведение: с фронта передаются данные из всех полей формы в стандартном формате(data: {"column1":"value1",...})

![image](https://user-images.githubusercontent.com/5404210/91154570-56aa3900-e6ca-11ea-85d2-44b692408549.png)
[динамическая форма(структура).txt](https://github.com/essence-community/core/files/5122561/default.txt)
[данные, которые отправляются с фронта.txt](https://github.com/essence-community/core/files/5122570/default.txt)

**Comment by toksy** [comment]
Реализован компонент 

Panel Nested 

Он позволит строить конструкции типа - 
Window
-Panel Nested 
--Box or panel -> здесь может быть самостоятельный сервис загрузки
---fileds...
-Panel Nested 
--Box or panel -> здесь может быть самостоятельный сервис загрузки
---fileds...
-button

Это позволит реализовать поведение подгрузки дополнительной части формы

**Comment by toksy** [comment]
Компонент реализован в - https://github.com/essence-community/core/releases/tag/2.6.2

прошу для подобных ситуаций использовать его
