### ISSUE TITLE
Ошибочное открытие вкладки при открытии окна (ПКО)

### ISSUE THREAD

**Issue by suijius** [essence-community/core#51]
1. Со страницы "Счета и выписки" со вкладки "Выписки" перейти по ссылке "Платёжное поручение" на страницу "Платёжное поручение" (см. screenshot):
http://pko-dev2.developers/page/22446861
2. В результате на странице "Платёжное поручение" откроется вкладка "История";
3. Должна открываться вкладка "Платёжное поручение".
![image](https://user-images.githubusercontent.com/3819104/93440109-f9279780-f8d7-11ea-8d6c-ddd0b126bd6f.png)

**Comment by toksy** [comment]
Предоставьте выгрузку страницы с элементарным поведением. 

Предоставьте сервис пустышку для начитки данных в гриды , для воспроизведения проблемы
