### ISSUE TITLE
Необходимо принудительно очищать выбранные строки грида с чекбоксами с соответствующей глобалкой (ПКО)

### ISSUE THREAD

**Issue by suijius** [essence-community/core#52]
Необходимо сбрасывать выбранные строки грида при смене условий поиска по фильтру, оставляя только те, которые удовлетворяют условиям фильтра.

**Comment by toksy** [comment]
Работа мультивыбора строится по принципу 
"отфильтровал - отметил - изменил фильтр - отметил - отправил в обработку" 

Отменить выбор можно, кликнув по всей колонке
