### ISSUE TITLE
Некорректное поведение при обновлении страницы "Платежное поручение" (ПКО)

### ISSUE THREAD

**Issue by suijius** [essence-community/core#53]
1. Открыть страницу "Счета и выписки", вкладка "Выписки"
2. Выбрать организацию и банк
3. Выбрать выписку
4. Выбрать документ в детализации
5. Открыть платежное поручение, есть 2 вкладки (Платежное поручение, История)
6. Нажать "Обновить страницу", осталась только вкладка История

**Comment by toksy** [comment]
Необходима выгрузка страницы с примерами сервисов для нее. 
или добавьте скриншоты... так понять о чем речь не представляется возможным

**Comment by toksy** [comment]
страница не предоставлена
