### ISSUE TITLE
Не заполняется комбобокс по значению из глобалки

### ISSUE THREAD

**Issue by alexey8pcd** [essence-community/core#58]
Глобалка есть и заполнена, сервис вызывается (но почему-то 2 раза, вместо одного), значение не подставляется, хотя становится доступно для выбора из комбобокса.
Работало в версии 2.2 (видно на скриншоте)

![image](https://user-images.githubusercontent.com/5404210/98541458-8831aa00-22a0-11eb-9bc3-7b2dc1122eb6.png)

**Comment by toksy** [comment]
Исправлено в версии 2.6.5
